export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const BOOKMARK_POST = "BOOKMARK_POST";

export const CHANGE_AVATAR_START = "CHANGE_AVATAR_START";
export const CHANGE_AVATAR_SUCCESS = "CHANGE_AVATAR_SUCCESS";
export const CHANGE_AVATAR_FAILURE = "CHANGE_AVATAR_FAILURE";
export const REMOVE_AVATAR_START = "REMOVE_AVATAR_START";
export const REMOVE_AVATAR_SUCCESS = "REMOVE_AVATAR_SUCCESS";
export const REMOVE_AVATAR_FAILURE = "REMOVE_AVATAR_FAILURE";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
